### ISSUE TITLE
ActionWebRequest datamodel

### ISSUE THREAD

**Issue by Hipska** [itomig-de/itomig-webhook-integration#13]
Why is the class `ActionWebRequest` defined in php code and not in the datamodel.xml file? It makes it harder to change or extend this class. If it would be changed, the parent for `ActionWebhookNotification` could then also be set more correctly.

**Comment by Molkobain** [comment]
Hello @Hipska ,

We are currently working on an implementation of the webhook actions directly in iTop (based on @larhip 's extension). Do you examples of what you would do if those classes were in the XML instead of being in PHP directly?

Guillaume

**Comment by Hipska** [comment]
It’s a datamodel item, so it should be in the xml anyway. So if you would want to extend or modify it, it would be possible with the xml. Also adding fields or changing display order should be possible.

**Comment by Hipska** [comment]
It could be done by the means of an intermediate php class `_ActionWebRequest` to be able to keep the methods in php file.

**Comment by Molkobain** [comment]
Exactly, thanks for your feedback.

**Comment by Hipska** [comment]
Can be closed as this will get there in Comodo's implementation.
