### ISSUE TITLE
New Feature: Add Modify and Lifecycle buttons to notification

### ISSUE THREAD

**Issue by larhip** [itomig-de/itomig-webhook-integration#4]
* Add three new options (AttributeEnum) to ActionSlackNotification class
	* Add modify button to notifications: yes/no
	* Add delete button to notifications: yes/no
	* Add lifecycle action buttons to notification: yes/no

* Based on selected options: add buttons to notifications:
	* Modify: ```
		elements[] = array(
			'type' => 'button',
			'test' => array(
				'type' => 'plain_text',
				'text' => 'Modify'
			),
			'url': '[link to modify object]'
		);```
	* Delete: ```
		elements[] = array(
			'type' => 'button',
			'test' => array(
				'type' => 'plain_text',
				'text' => 'Delete'
			),
			'url': '[link to delete object]'
		);```
	* Lifecycle Actions: ```
		elements[] = array(
			'type' => 'button',
			'test' => array(
				'type' => 'plain_text',
				'text' => 'Lifecycle action'
			),
			'url': '[link for lifecycle action]'
		);
		elements[] = [...];```

**Comment by Hipska** [comment]
Hi Lars, I have seen that you made this options in the parent class `ActionWebhookNotification` but not in `ActionSlackNotification`. Since these buttons are only possible with Slack, would it not be better to add these fields in the correct subclass?

**Comment by larhip** [comment]
Hi Thomas,
yes I decided to add the attributes to the parent class `ActionWebhookNotification` and the concret logic so just the methods to `ActionSlackNotification`.
Add the moment there is just this possibility in Slack but it might be that in the future there is a similar feature in RocketChat (Honestly speaking: I don not whether there is at the moment).
So I think that there is a high probability that we want to use those fields in RocketChat (or any other finalclass in the future?) as well. This is the reason why I decided to implement to attributes in the parent class.
Are you okay with it or do you have any reasons why it is not such a good idea?

**Comment by Hipska** [comment]
I was only wondering for the method fields, as this is not (yet) possible with rocket.chat. For #3 it is fine, as this can already be done in rocket.chat.

**Comment by larhip** [comment]
Will be integrated in next release (19.3.0)

**Comment by Hipska** [comment]
I think this can be closed since 18c9e4ca0284a9ee07b0dbe616d2801823950981.

**Comment by larhip** [comment]
Jep, you're right. I close this one.
