### ISSUE TITLE
New Feature: Add default notification text

### ISSUE THREAD

**Issue by Hipska** [itomig-de/itomig-webhook-integration#6]
What do you think if basic text is left empty (or with option) to add a default text:

> Object [R-00001](http://example.com/itop/pages/UI.php?operation=details&class=UserRequest&id=1) is created.

Or
> Object [R-00001](http://example.com/itop/pages/UI.php?operation=details&class=UserRequest&id=1) has been updated from portal.

Or even
> User Request [R-00001](http://example.com/itop/pages/UI.php?operation=details&class=UserRequest&id=1) status changed to **Assigned**.

Text could be saved in dictionary, for example:
`class:TriggerOnStateEnter/Notification` = `%1$s %2$s status changed to <b>%3$s</b>.`

1. Class translation
2. Object hyperlink
3. More info

With this, there is no need to create a separate action anymore for every type of trigger or for every type of object you want to make.

What are your thoughts on this?

**Comment by larhip** [comment]
Maybe this is something which is interesting to discuss with combodo directly. maybe this could be integrated in the core of itop with a new type of placeholder. The gives the opportunity to use such text messages not just in the notification type but also in email notifications for example.

**Comment by Hipska** [comment]
Yes, good idea but that will tak time.

Couldn't we do it already in the meantime?

**Comment by larhip** [comment]
Hi @Hipska ,
I discussed this with a colleague yesterday and we decided to not implement this in this extension.
From our point of view this feature definitely belongs to the implementation of the trigger and not of the actions. So I will close this issue.
Anyhow, thank you a lot for your proposal!
Best Lars

**Comment by Hipska** [comment]
Okay, good point.

**Comment by Hipska** [comment]
@Molkobain, what do you think of this? This would even be interesting to be used as title for email notifications..

**Comment by Molkobain** [comment]
Hello @Hipska ,

I'm not sure to understand where this would be used? That would be a default text to be used by the action in the body (for email actions) or payload (for webhook actions) ?

Idea seems interesting indeed! This would allow easier/faster notification configuration for the basic ones.
@v-dumas what do you think?

**Comment by Hipska** [comment]
Yes indeed. I was thinking to make it available as a [placeholder](https://www.itophub.io/wiki/page?id=2_7_0%3Aadmin%3Aplaceholders)
